### ISSUE TITLE
The packaged Vue3 component props. ts cannot call the props. ts type properly

### ISSUE THREAD

**Issue by InfernalAzazel** [unjs/mkdist#247]
### Environment

os: Ubuntu 22.04 
node: v20.17.0
vue: 3.4.37
unbuild: 2.0.0

### Reproduction

[reproduce](https://github.com/InfernalAzazel/k-naiveui-pro.git)
[docs]

### Describe the bug

1. The packaged Vue3 component props. ts cannot call the props. ts type properly
2. I don't know why the components encapsulated in dist compiled from docs can still be used normally
3.  Uncaught SyntaxError: The requested module '/@fs/work/kylin/github/k-naiveui-pro/packages/k-naiveui-pro/dist/components/ProBaseForm/index.mjs' does not provide an export named 'ProBaseFormColumn' (at ProBaseForm.vue:3:28)

### Additional context

1. pnpm docs:dev (Exception occurred)
![image](https://github.com/user-attachments/assets/d798691d-e805-4f86-bca0-daaca7a5806f)

2.Compile dist and upload it to GitHub page(natural)
![image](https://github.com/user-attachments/assets/d0bc8d48-cd80-4e76-81a9-491861301f9e)

### Logs

```sh
Uncaught SyntaxError: The requested module '/@fs/work/kylin/github/k-naiveui-pro/packages/k-naiveui-pro/dist/components/ProBaseForm/index.mjs' does not provide an export named 'ProBaseFormColumn' (at ProBaseForm.vue:3:28)
```

**Comment by Teages** [comment]
`<script setup>` are closed, it means your type export would not work as you want.
move them to a non-setup script could fix it.

```vue
<script lang="ts">
export interface xxx {}
</script>
```
